name: build

on:
  push:
    branches: [main, dev, dev-reuse]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the image
        run: |
          docker buildx build --push \
          --tag cob2k25/mvsce:latest \
          --tag cob2k25/mvsce:${{github.sha}} \
          --platform linux/amd64,linux/arm64 .
